# This field is customizable.
ds:
  port: 8888
ps: 
  port: 5433

spring:
  # add kafka configurations below spring
  datasource:
    url: jdbc:postgresql://postgres:${ps.port}/crm
    # This field is customizable.
    username: postgres
    # This field is customizable.
    password: test
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

# Local host server port, can be changed
server:
  # This field is customizable.
  port: 8089

jwt:
  expiration: 60000000
  secret: 9W6ch2K/rgdYy88op9r+eUu+88BOifC1etCkUtXa3sQQ+p9/oCc/7Pkra0NLzKeAwg91u7+Guhms2sm75oUYNXNFHWvkExFTlM3hzOrRQukzyOwsP0Hcr7kC2Z6c7w9blaWblOyLEaVr7l1H9ib/Ig5t+3xOB4avL4B/0c/PWua1ZB0ykbz9J+Pz+twKYWk4VCfW3AoCZTlCgbOBaw979E14iV91gY0bju7Hti+3wctW1f9JzFi+V7oR0w632Zg9RAve/plSD/KAQ3OY5aserGmXfXzb8hvb2qBusvl76L3LY5p/D2FxZEUzM3t8SnBjDxxJZOS3J+JaqN3pW9YSqKpr51MjAY+6r5oPYonEt60=


eureka:
  client:
    serviceUrl:
      # This field port is customizable, if it changed eureka routes must be changed as well.
      defaultZone: http://discovery-server:${ds.port}/eureka/
    registerWithEureka: true
    fetchRegistry: true
