ds:
  port: 8888

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: customerservice
            uri: lb://customerservice
            predicates:
              - Path=/api/v1/customers/**
          - id: eureka
            uri: http://localhost:${ds.port}
            predicates:
              - Path=/eureka/web
            filters:
              - SetPath=/
          - id: eureka-static
            uri: http://localhost:${ds.port}
            predicates:
              - Path=/eureka/**
          
server:
  # This field is customizable.
  port: 8090

eureka:
  client:
    serviceUrl:
      # This field port is customizable, if it changed eureka routes must be changed as well.
      defaultZone: http://localhost:${ds.port}/eureka/
    registerWithEureka: true
    fetchRegistry: true
